name: Check TODO
on: [push, pull_request]
jobs:
  todo:
    runs-on: ${{ matrix.os }}
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
      #    env:
      #      OS: ${{ matrix.os }}
      #      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tdg-github-action
        uses: ribtoks/tdg-github-action@v0.4.13-beta
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          COMMENT_ON_ISSUES: true
